### ISSUE TITLE
D1 items not showing 

### ISSUE THREAD

**Issue by Planetmachine** [Dcai169/Destiny-API-Ripper-Extension#13]
Im having an issue where choosing the d1 items in the dropdown box is not loading anything. I have tired redownloading, and on my laptop as well, but cannot access. I noticed the latest version fixes this. so im not sure why i am getting this. 

im running on v 1.6.1 
windows 11

Thanks! - Planetmachine

**Comment by Dcai169** [comment]
Hello!

Please start DARE and press `Ctrl+Shift+I`. Then switch to the `Console` tab then attempt to switch to Destiny 1. If an error occurs, please share it in this thread.

**Comment by Planetmachine** [comment]
I wasnt sure how to paste code here, but i got two errors pop up. here is a screenshot


![Screenshot_20221225_064942](https://user-images.githubusercontent.com/121305882/209486629-54fa6432-be0e-4b05-b1dc-b0bf0dc63c44.png)

**Comment by Dcai169** [comment]
This issue is because the old method of accessing D1 items is now unavailable, and a new method will be implemented soon.
